### ISSUE TITLE
[request] 486 support eol... possibility to use mmuless linux kernel?

### ISSUE THREAD

**Issue by prozacgod** [marmolak/gray486linux#1]
Since 486 is probably going EOL and 6.1 will be the last kernel version to support it, or perhaps a later (but not much later) timeframe

I was wondering if you might be interested in getting an MMU-less variant of the kernel to work on a 486, I .. don't really understand all the technical features the 486 is missing compared to modern platforms.  But it occurred to me perhaps, the mmu-less variant of linux would work fine, in a single-user style setup.

it may not technically be achievable, but hopefully the idea interests you!

**Comment by marmolak** [comment]
Hi. I still hope that 6.2 going to still support 486.
Then maybe, It will be still possible to revert nuke patch for 486 and maybe still force 6.2 to work on 486. Tons of maybe for now.

However, gray486linux is single user not single process. So MMU is still important for protecting processes memory spaces, even if root can modify them all (but not by accident). Also, MMU is part of 486 so why not to use it? :)

However thank you for interesting part to study :).
For example:
https://www.kernel.org/doc/html/latest/admin-guide/mm/nommu-mmap.html

**Comment by marmolak** [comment]
Hi. Kernel 6.2 is still 486 friendly \o/.

Would it be possible to close this issue at this time?

**Comment by marmolak** [comment]
Closing for now. Feel free to reopen.

**Comment by prozacgod** [comment]
Huzzah!
