### ISSUE TITLE
Docker build environment

### ISSUE THREAD

**Issue by prozacgod** [marmolak/gray486linux#2]
Would you be interested in a Docker based building environment, I was debating on doing something like that, just figured I'd get some feedback before I do it.  Any thoughts on how you'd like it to work/etc

**Comment by marmolak** [comment]
Hi! Sounds great.
Thank you for good idea.

Will you handle this itself?

Do you mean container with Nix build env included or just manual compilation of everything?

**Comment by prozacgod** [comment]
At first, I want to get a docker container to build off the kernel itself.  But I'm more than happy to figure out all the details.  I supposed my initial goal is to "just follow your build steps, but automate them in a docker container"  I'll fork the project and spend some time on it this weekend.

**Comment by prozacgod** [comment]
I should say, I'm vastly new to NixOS and oversimplified it in my head, I hadn't considered how all the nuance of the tool you're already using.  *ehem* so ... I just didn't want to have a bunch of stuff installed on my local machine to do the work, and assumed getting it into a docker container is well within my knowledge.

Feel free to tell me if I'm already off course ;)

**Comment by marmolak** [comment]
Great. I had some time so I just sketched:
https://github.com/marmolak/gray486linux/commit/f8c9d8ec0a4bdfa9d8e6e77118e5b1b7202cf9d7

Totally not finished nor tested. However it can be good ground to make it usable.

**Comment by prozacgod** [comment]
Hey I just got some time to peak at that, the dockerfile looks great to me, it actually covers my needs perfectly fine.  I don't get a lot of time to do my hobbies as much so I'll look into it and see if it helps with the development I was wanting to do next.  Probably get back to you in a few days.

**Comment by marmolak** [comment]
Ok. I added Dockerfile and shell helpers so this issue should be closed.

**Comment by prozacgod** [comment]
First, thank you so much for putting time into this!  I managed to run it in docker, I'm not familiar with podman, and don't have/use it.

I built it in docker with

docker build -t build_gray486linux .

and then ran it from the docker folder with

docker run -v $PWD/..:/build build_gray486linux

This lead me to a nitpick with the dockerfile

instead of 
RUN ./graybuild.sh

it should be 
ENTRYPOINT ./graybuild.sh


This is because the idea of the docker image in this context is a "unified collection of tools that can build the result on demand" and that demand is the "execution of the docker instance"

I looked into the podman execution as well and I think that is 100% compatible with the way your current build script works.

Also it would be nice to either have a build_docker.sh / run_docker.sh or at least documentation for those who don't have podman, I wasnt familiar with it.

But!! best of all It worked great for me, and I'm happy with the output!  Thanks a bunch!

**Comment by marmolak** [comment]
Hi.

Thank you for feedback. I played with podman/docker and here is some proposed improvements:
https://github.com/marmolak/gray486linux/commit/6e400ffd4976c35f5bca8ac180f591ccf93b9931

I removed `--no-cache`, because rebuild is fast - you don't need to rebuild compiler and distro every time.
Also ENTRYPOINT makes things clear from my POV, so thank you for pinning this out.

Documentation is work in progress and using `graybuild.sh` and `grayrun.sh` can be confusing.

**Comment by marmolak** [comment]
I just added:

https://github.com/marmolak/gray486linux/commit/d36797456a72057ab797d09a8b5a82b45b61ad5a
which should work fine. At least it works fine for me :).

**Comment by prozacgod** [comment]
That looks good, I think it works - didn't have a chance to run it.  I've been away from home waiting for a giant rocket to launch :P

Secondarily the machine that I was wanting to make all this work on, sadly... died :/  I had an old Omnibook 425 and was really stoked to try to get some linux working on it.

I have a few other old 486 machines I can get up and running to fiddle with this on.  but won't have more feedback until then. Everything is looking great thanks so much, I'll have to get you some boot videos of my 486 machines launching this on my yt channel sometime!

**Comment by marmolak** [comment]
Thank you. Ok. So I need to add changes to gray386linux now :).

Closing as solved.

PS: Please, don't hesitate and let me know about your videos.
